### ISSUE TITLE
Black screen issue

### ISSUE THREAD

**Issue by uzairblaoch** [duydoan1411/gl553vd-opencore-macos-big-sur#1]
It boots into black screen 
I notice it does boot but only appears blackscreen
![F1EDEC74-D548-4B16-8516-433B4CD0DD59](https://user-images.githubusercontent.com/59788761/99539151-b2394980-29cf-11eb-8f57-56774aa8e708.jpeg)

**Comment by zonetvs** [comment]
Try reset NVRAM.

**Comment by duydoan1411** [comment]
From the picture I can see you are using a dell laptop but this is OC for Asus ROG Gl553VD.
I think you need to show verbose in boot screen. You can add "-v" into boot args. 
And then, you can search for the solution to the current error.

**Comment by duydoanx** [comment]
From the picture I can see you are using a laptop dell, but here is OC for ROG GL553VD.
I think you need to show verbose in boot screen. You can add "-v" into boot args. 
And then, you can search for the solution to the current error.

**Comment by uzairblaoch** [comment]
It’s dell. Inspiron 5577 
Core i7-7700hq (kaby lake) 
I fixed it by spoofing skylake id and -disablegfxfirmware and lilucup 8
