### ISSUE TITLE
Please add your edited .dsl files to the repo

### ISSUE THREAD

**Issue by urherenow** [duydoan1411/gl553vd-opencore-macos-big-sur#3]
Needed in case of changes in newer versions of OpenCore, laptop firmware, etc., and so I may gain a clue on how you got the battery working. I failed trying to follow manual instructions...

Couple of additional items:

Wireless was not working with this setup (I'm on Catalina though), but I replaced your Itlwm.kext with AirportItlwm.kext (_v1.2.0_stable_Catalina) and it works perfectly now.

Clicking with the touchpad registers as a right-click. Currently working around that by going into settings and enabling single tap for click (and enabled 2 finger tap for right-click). So apparently multi-touch works and scrolling works, but the button on either side registers as a right-click.

It also seems OpenCore is out of date here, thus some of the config.plist entries. 

At any rate, my battery seems to work, touchpad works (except for the problem mentioned above), so thank you so much for sharing this!

**Comment by duydoanx** [comment]
I have updated to opencore version 0.6.9
