### ISSUE TITLE
 WebCam Driver

### ISSUE THREAD

**Issue by SeiElikA** [duydoan1411/gl553vd-opencore-macos-big-sur#4]

**Comment by SeiElikA** [comment]
How Can you use this WebCam

**Comment by duydoanx** [comment]
You can follow this tutorial https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html
Or using USBInjectAll kext

**Comment by SeiElikA** [comment]
OK! very ThenkYou.

**Comment by duydoanx** [comment]
You can try the latest version I just commited.
